[package]
name = "helix"
version = "1.0.0"
license = "GPL-3.0-or-later"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["macos-private-api"] }
tauri-plugin-dialog = "2"
tauri-plugin-window-state = "2"
percent-encoding = "2"
objc2 = "0.6"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
